export enum ChatEventEnum {
  CONNECTED_EVENT = "connected",
  DISCONNECTED_EVENT = "disconnected",
  JOIN_CHAT_EVENT = "joinChat",
  JOIN_USER_GROUPS_EVENT = "join_user_groups",
  LEAVE_CHAT_EVENT = "leaveChat",
  UPDATE_GROUP_NAME_EVENT = "updateGroupName",
  MESSAGE_RECEIVED_EVENT = "messageReceived",
  MESSAGE_DELETE_EVENT = "messageDeleted",
  NEW_CHAT_EVENT = "newChatEvent",
  SOCKET_ERROR_EVENT = "socketError",
  START_TYPING_EVENT = "startTyping",
  STOP_TYPING_EVENT = "stopTyping",
  MESSAGE_READ_EVENT = "messageRead",
  MESSAGE_DELIVERED_EVENT = "messageDelivered",
  MESSAGE_STATUS_UPDATE_EVENT = "messageStatusUpdate",
  MESSAGE_SENT_EVENT = "messageSent",
  MESSAGE_FAILED_EVENT = "messageFailed",
  NOTIFICATION_EVENT = "notification",
  CONVERSATION_UPDATED = "conversationUpdated",
  CONVERSATION_READ = "conversationRead",
  USER_STATUS_UPDATE = "userStatusUpdate",
  USER_ONLINE = "userOnline",
  USER_OFFLINE = "userOffline",
}
